/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,ts,tsx,mdx,js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#0d0d0d',
        foreground: '#f5f5f5',
        card: '#161616',
        'card-foreground': '#f5f5f5',
        popover: '#161616',
        'popover-foreground': '#f5f5f5',
        primary: '#7c3aed',
        'primary-foreground': '#fafafa',
        secondary: '#1e1e1e',
        'secondary-foreground': '#a3a3a3',
        muted: '#262626',
        'muted-foreground': '#737373',
        accent: '#7c3aed',
        'accent-foreground': '#fafafa',
        destructive: '#ef4444',
        'destructive-foreground': '#fafafa',
        success: '#10b981',
        'success-foreground': '#fafafa',
        warning: '#f59e0b',
        'warning-foreground': '#0d0d0d',
        border: '#262626',
        input: '#262626',
        ring: '#7c3aed',
        'bg-surface': '#161616',
        'bg-elevated': '#1e1e1e',
        'text-primary': '#f5f5f5',
        'text-secondary': '#a3a3a3',
        'text-muted': '#737373',
        'text-terminal': '#4ade80',
        'status-queued': '#737373',
        'status-running': '#7c3aed',
        'accent-hover': '#6d28d9',
        'accent-light': '#a78bfa',
      },
      borderRadius: {
        sm: '0.375rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      keyframes: {
        orbit: {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
        glow: {
          '0%, 100%': { opacity: '0.4' },
          '50%': { opacity: '1' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-12px)' },
        },
        'slide-up': {
          from: { opacity: '0', transform: 'translateY(24px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        'gradient-shift': {
          '0%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
          '100%': { backgroundPosition: '0% 50%' },
        },
        twinkle: {
          '0%, 100%': { opacity: '0.2' },
          '50%': { opacity: '1' },
        },
      },
      animation: {
        orbit: 'orbit 8s linear infinite',
        glow: 'glow 3s ease-in-out infinite',
        float: 'float 6s ease-in-out infinite',
        'slide-up': 'slide-up 0.6s ease-out both',
        'fade-in': 'fade-in 0.5s ease-out both',
        gradient: 'gradient-shift 6s ease infinite',
        twinkle: 'twinkle 4s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
